export {
  DEFAULT_RENDERER_CONFIG,
  DEFAULT_CAMERA_CONFIG,
  DEFAULT_ORBIT_CONTROLS_CONFIG,
  DEFAULT_PERFORMANCE_CONFIG,
  DEFAULT_POST_PROCESSING_CONFIG,
  DEFAULT_ENVIRONMENT_CONFIG,
  DEFAULT_FOG_CONFIG,
} from './rendering';

export { STAR_DENSITY_CONFIGS } from './stars';
export { NEBULA_DENSITY_CONFIGS } from './nebula';
