import { RepositoryDomainModel } from '@/domain/RepositoryModels';
import { UniverseBuilder } from './UniverseBuilder';

export const SAMPLE_REPOSITORIES: RepositoryDomainModel[] = [
  {
    id: 'repo-netflix-zuul',
    name: 'zuul-api-gateway',
    owner: 'netflix',
    description:
      'Edge API Gateway and Intelligent Routing Service for Cloud Infrastructure',
    size: 45200,
    stars: 12450,
    forks: 2310,
    issues: 14,
    commits: 3420,
    pullRequests: 420,
    releases: 34,
    primaryLanguage: 'TypeScript',
    languages: [{ name: 'TypeScript', color: '#3178C6', percentage: 92 }],
    topics: ['api-gateway', 'microservices', 'routing', 'security'],
    techStack: ['Node.js', 'Express', 'Redis', 'Docker'],
    contributors: [{ username: 'octocat', commits: 340 }],
    healthScore: { overall: 94, activity: 92, community: 95, maintenance: 95 },
    complexityScore: 42,
    createdAt: '2024-01-15T00:00:00Z',
    updatedAt: '2026-07-30T12:00:00Z',
    isArchived: false,
    visibility: 'public',
  },
  {
    id: 'repo-netflix-eureka',
    name: 'eureka-discovery-server',
    owner: 'netflix',
    description:
      'REST based service for locating services for load balancing and failover',
    size: 32100,
    stars: 8900,
    forks: 1820,
    issues: 8,
    commits: 2190,
    pullRequests: 210,
    releases: 28,
    primaryLanguage: 'TypeScript',
    languages: [{ name: 'TypeScript', color: '#3178C6', percentage: 88 }],
    topics: ['service-discovery', 'cloud', 'resilience'],
    techStack: ['TypeScript', 'gRPC', 'Etcd'],
    contributors: [{ username: 'developer', commits: 180 }],
    healthScore: { overall: 91, activity: 88, community: 92, maintenance: 93 },
    complexityScore: 35,
    createdAt: '2024-03-10T00:00:00Z',
    updatedAt: '2026-07-29T15:30:00Z',
    isArchived: false,
    visibility: 'public',
  },
  {
    id: 'repo-sentinel-ops',
    name: 'sentinel-observability-engine',
    owner: 'sentinel',
    description:
      'High-throughput Autonomous Telemetry & Distributed Tracing Pipeline',
    size: 89400,
    stars: 15600,
    forks: 3100,
    issues: 22,
    commits: 5120,
    pullRequests: 680,
    releases: 45,
    primaryLanguage: 'Go',
    languages: [{ name: 'Go', color: '#00ADD8', percentage: 95 }],
    topics: ['telemetry', 'metrics', 'tracing', 'opentelemetry'],
    techStack: ['Go', 'Kafka', 'Prometheus', 'ClickHouse'],
    contributors: [{ username: 'lead-dev', commits: 920 }],
    healthScore: { overall: 96, activity: 95, community: 97, maintenance: 96 },
    complexityScore: 58,
    createdAt: '2023-11-01T00:00:00Z',
    updatedAt: '2026-07-31T09:15:00Z',
    isArchived: false,
    visibility: 'public',
  },
  {
    id: 'repo-auth-vault',
    name: 'cyber-vault-authenticator',
    owner: 'sentinel',
    description:
      'Zero-Trust Identity Authentication and Cryptographic Key Management',
    size: 28900,
    stars: 7400,
    forks: 980,
    issues: 3,
    commits: 1840,
    pullRequests: 140,
    releases: 19,
    primaryLanguage: 'Rust',
    languages: [{ name: 'Rust', color: '#DEA584', percentage: 98 }],
    topics: ['security', 'vault', 'zero-trust', 'oauth2'],
    techStack: ['Rust', 'WebAssembly', 'PKCS11'],
    contributors: [{ username: 'security-lead', commits: 410 }],
    healthScore: { overall: 98, activity: 94, community: 99, maintenance: 99 },
    complexityScore: 64,
    createdAt: '2024-05-18T00:00:00Z',
    updatedAt: '2026-07-30T18:40:00Z',
    isArchived: false,
    visibility: 'public',
  },
  {
    id: 'repo-payment-ledger',
    name: 'core-payment-ledger-api',
    owner: 'stripe',
    description:
      'Double-entry Transactional Ledger Engine & Multi-currency Settlement',
    size: 112000,
    stars: 21300,
    forks: 4800,
    issues: 5,
    commits: 9810,
    pullRequests: 1120,
    releases: 82,
    primaryLanguage: 'Python',
    languages: [{ name: 'Python', color: '#3572A5', percentage: 90 }],
    topics: ['payments', 'ledger', 'financial-graph', 'compliance'],
    techStack: ['Python', 'FastAPI', 'PostgreSQL', 'Temporal'],
    contributors: [{ username: 'fintech-eng', commits: 1420 }],
    healthScore: { overall: 99, activity: 98, community: 99, maintenance: 100 },
    complexityScore: 72,
    createdAt: '2023-08-12T00:00:00Z',
    updatedAt: '2026-07-31T11:00:00Z',
    isArchived: false,
    visibility: 'private',
  },
];

export class SampleUniverseBuilder {
  public static loadSampleUniverse(): void {
    UniverseBuilder.build(SAMPLE_REPOSITORIES);
  }
}
